context:
  dataset: ~
  efficiency_file: ~
  xsections_file: ~
  modelName: ~
stages:
  - name: download
    parameters:
      dataset: '{dataset}'
      outDir: '/workdir/grid_download'
      outList: '/workdir/files.list'
    scheduler:
      scheduler_type: 'single-from-ctx'
      step: {$ref: 'common_steps/downloadnode.yml'} 
  - name: ntupling
    dependencies:
      - download
    parameters:
      minintup: '/workdir/mini.root'
      maxsyst: 1
      input_type: '-mc'
      filter: '-nomllalpgenfilter'
      blinded: '-unblind'
      include_truth: '-truth'
    scheduler:
      scheduler_type: 'reduce-from-dep'
      step: {$ref: 'ewksusy_steps/ntupling.yml'}
      from_stages:
        - download
      outputs: output
      to_input: filelist
  - name: histfitprepare
    dependencies:
      - ntupling
    parameters:
      efficiency_file: '{efficiency_file}'
      xsections_file: '{xsections_file}'
      modelName: '{modelName}'
      histfittree_file: '/workdir/out.root'
      yield_file: '/workdir/out.yield'
    scheduler:
      scheduler_type: 'reduce-from-dep'
      step: {$ref: 'ewk_analyses/ewkdilepton_analysis/histfitprep.yml'}
      from_stages:
        - ntupling
      outputs: output
      to_input: miniroot
  - name: fit
    dependencies:
      - histfitprepare
    parameters:
      fitresults: '/workdir/fit.tgz'
    scheduler:
      scheduler_type: 'reduce-from-dep'
      step: {$ref: 'ewk_analyses/ewkdilepton_analysis/fit.yml'}
      from_stages:
        - histfitprepare
      outputs: output_tree
      to_input: histfitroot
  - name: postproc
    dependencies:
      - fit
    parameters:
      workdir: '/workdir/postproc'
      modelName: '{modelName}'
      resultsyaml: '/workdir/results.yaml'
    scheduler:
      scheduler_type: 'reduce-from-dep'
      step: {$ref: 'ewk_analyses/ewkdilepton_analysis/postproc.yml'}
      from_stages:
        - fit
      outputs: output
      to_input: fitresultsarchive