stages:
  - name: hello
    dependencies: []
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        parone: 'WORLD'
      step: {$ref: 'steps.yml#/hello'}
  - name: world
    dependencies: ['hello']
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        parone: 'HELLO'
        partwo: {stages: hello, output: hello, unwrap: true}
      step: {$ref: 'steps.yml#/world'}
  