context:
  events: ~
  rivet_analysis: ~
stages:
  - name: prepare
    parameters:
      model: sm
      parametercard: '/workdir/param.dat'
      inputpars: defaultparam.yml
    scheduler:
      scheduler_type: 'single-from-ctx'
      step: {$ref: 'pheno_workflows/preparestep.yml'}
  - name: madgraph
    dependencies:
      - prepare
    parameters:
      outputlhe: '/workdir/output.lhe'
      events: '{events}'
    scheduler:
      scheduler_type: 'reduce-from-dep'
      step: {$ref: 'pheno_workflows/madgraph.yml'}
      from_stages:
        - prepare
      outputs: parcard
      to_input: paramcard
  - name: pythia
    dependencies:
      - madgraph
    parameters:
      outputhepmc: '/workdir/output.hepmc'
      events: '{events}'
    scheduler:
      scheduler_type: 'reduce-from-dep'
      step: {$ref: 'pheno_workflows/pythia.yml'}
      from_stages:
        - madgraph
      outputs: lhefile
      to_input: lhefile
  - name: rivet
    dependencies:
      - pythia
    parameters:
      outputyoda: '/workdir/output.yoda'
      analysis: '{rivet_analysis}'
    scheduler:
      scheduler_type: 'reduce-from-dep'
      step: {$ref: 'pheno_workflows/rivet.yml'}
      from_stages:
        - pythia
      outputs: hepmcfile
      to_input: inputhepmc
  - name: plots
    dependencies:
      - rivet
    parameters:
      yodaplots: '/workdir/plots'
    scheduler:
      scheduler_type: 'reduce-from-dep'
      step: {$ref: 'pheno_workflows/rivetplot.yml'}
      from_stages:
        - rivet
      outputs: yodafile
      to_input: inputyoda

