context:
  myparameter: ~
  a_list: ~
stages:
  - name: data_acquisition
    parameters:
      parameter_one: '{myparameter}'
    scheduler:
      scheduler_type: 'single-from-ctx'
      step: {$ref: 'dummy_analysis/dataacquisition.yml'} 
  - name: data_acquisition2
    parameters:
      parameter_two: '{a_list}'
      parameter_out: 'theoutput_{index}'
    scheduler:
      scheduler_type: 'map-from-ctx'
      step: {$ref: 'dummy_analysis/mappingstep.yml'} 
      map_parameter: parameter_two
      to_input: inputpar
  - name: mapstage
    dependencies:
      - data_acquisition
    parameters:
      parameter_out: 'theoutput_{index}'
    scheduler:
      scheduler_type: 'map-from-dep'
      step: {$ref: 'dummy_analysis/mappingstep.yml'}
      from_stages:
        - data_acquisition
      outputs: acq_out
      to_input: inputpar
  - name: mapstage2
    dependencies:
      - mapstage
    parameters:
      parameter_out: 'anotheroutput_{index}'
    scheduler:
      scheduler_type: 'map-from-dep'
      step: {$ref: 'dummy_analysis/mappingstep.yml'}
      from_stages:
        - mapstage
      outputs: output
      to_input: inputpar
  - name: reduce
    dependencies:
      - mapstage
    parameters:
      out: mergedfile.root
    scheduler:
      scheduler_type: 'reduce-from-dep'
      step: {$ref: 'dummy_analysis/reducestep.yml'}
      from_stages:
        - mapstage
      outputs: output
      to_input: in
  - name: reduce2
    dependencies:
      - mapstage2
    parameters:
      out: mergedfile2.root
    scheduler:
      scheduler_type: 'reduce-from-dep'
      step: {$ref: 'dummy_analysis/reducestep.yml'}
      from_stages:
        - mapstage2
      outputs: output
      to_input: in
  - name: reduce3
    dependencies:
      - data_acquisition2
    parameters:
      out: mergedfile3.root
    scheduler:
      scheduler_type: 'reduce-from-dep'
      step: {$ref: 'dummy_analysis/reducestep.yml'}
      from_stages:
        - data_acquisition2
      outputs: output
      to_input: in
  - name: metareduce
    dependencies:
      - reduce
      - reduce2
      - reduce3
    parameters:
      out: mergedfile3.root
    scheduler:
      scheduler_type: 'reduce-from-dep'
      step: {$ref: 'dummy_analysis/reducestep.yml'}
      from_stages:
        - reduce
        - reduce2
        - reduce3
      outputs: reduced
      to_input: in