context:
  inputparameter: ~
  outputparameter: ~
stages:
  - name: dummystage
    parameters:
      input: '{inputparameter}'
      output: '{outputparameter}'
    scheduler:
      scheduler_type: 'single-from-ctx'
      step:
        process:
          process_type: 'string-interpolated-cmd'
          cmd: 'echo {input} {output}'
        publisher:
          publisher_type: 'frompar-pub'
          outputmap:
            step_output: output
        environment:
          environment_type: 'docker-encapsulated'
          image: busybox
