context:
  dummyvalue: ~
stages:
  - name: init
    parameters:
      parameter_one: '{dummyvalue}'
    scheduler:
      scheduler_type: 'single-from-ctx'
      step: {$ref: 'dummy_analysis/dummystep.yml'}
  - name: zip
    dependencies:
      - init
    parameters: {}
    scheduler:
      scheduler_type: 'zip-from-dep'
      step: {$ref: 'dummy_analysis/take_four_pars.yml'}
      zip:
        - from_stages:
          - init
          outputs: 'multiple'
          zip_with: ['par1','par2','par3']
        - from_stages:
          - init
          outputs: 'single'
          zip_with: ['par4']