stages:
  - name: gendata
    dependencies: []
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        outfilename: '{workdir}/data.root'
      step: {$ref: 'steps.yml#/gendata'}
  - name: fitdata
    dependencies: ['gendata']
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        data: {stages: gendata, output: data, unwrap: true}
        outfile: '{workdir}/plot.png'
      step: {$ref: 'steps.yml#/fitdata'}