stages:
  - name: prepare
    dependencies: ['init']
    scheduler:
      scheduler_type: singlestep-stage
      step: {$ref: 'steps.yml#/prepare'}
      parameters:
        kHzz: {stages: init, output: kHzz}
        kAzz: {stages: init, output: kAzz}
        kHww: {stages: init, output: kHww}
        kAww: {stages: init, output: kAww}
        param_card: '{workdir}/param.dat'

  - name: grid
    dependencies: ['prepare']
    scheduler:
      scheduler_type: singlestep-stage
      step: {$ref: 'steps.yml#/grid'}
      parameters:
        param_card: {stages: prepare, output: param_card}
        gridpack: '{workdir}/grid.tar.gz'

