stages:
  - name: madevent
    dependencies: ['init']
    scheduler:
      scheduler_type: singlestep-stage
      step: {$ref: 'steps.yml#/madgraph'}
      parameters:
        gridpack: {stages: init, output: gridpack}
        nevents: {stages: init, output: nevents}
        seed: {stages: init, output: seed}
        lhefile: '{workdir}/lhefile.lhe'
    
  - name: pythia_delphes
    dependencies: ['madevent']
    scheduler:
      scheduler_type: singlestep-stage
      step: {$ref: 'steps.yml#/pythia'}
      parameters:
        lhefile: {stages: madevent, output: lhefile}
        pythia_settings_file: /analysis/mainPythiaMLM.cmnd
        delphes_detector_card: /analysis/template_cards/modified_delphes_card_ATLAS.tcl
        outputfile: '{workdir}/outputfile.root'
        
  - name: analysis
    dependencies: ['delphes']
    scheduler:
      scheduler_type: singlestep-stage
      step: {$ref: 'steps.yml#/analysis'}
      parameters:
        fromdelphes: {stages: delphes, output: delphesoutput}
        analysis_output: '{workdir}/anaout.root'
