context:
  inputdatasets: ~
stages:
  - name: data_acquisition
    parameters:
      inputs: '{inputdatasets}'
    scheduler:
      scheduler_type: 'single-from-ctx'
      step: {$ref: 'lhcb_talk/dataacquisition.yml'} 
  - name: mapstage
    dependencies:
      - data_acquisition
    parameters:
      output: 'output_{index}'
    scheduler:
      scheduler_type: 'map-from-dep'
      step: {$ref: 'lhcb_talk/mappingstep.yml'}
      from_stages:
        - data_acquisition
      outputs: acq_out
      to_input: input
  - name: reduce
    dependencies:
      - mapstage
    parameters:
      out: mergedfile.root
    scheduler:
      scheduler_type: 'reduce-from-dep'
      step: {$ref: 'lhcb_talk/reducestep.yml'}
      from_stages:
        - mapstage
      outputs: map.*
      to_input: in